on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Pipeline CI
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Lint
      uses: egonbraun/python-lint-action@v1.1.0
    - name: Test
      uses: egonbraun/python-unittest-action@v1.1.0
    - name: Build
      uses: egonbraun/python-build-action@v1.0.0
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: |
          dist/*.tar.gz
          dist/*.whl
  cd:
    runs-on: ubuntu-latest
    name: Pipeline CD
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-artifacts
        path: dist
    - name: Release
        uses: egonbraun/python-release-action@v1.0.0
